In [1]:
import pandas as pd
import numpy as np

In [2]:
row_data=pd.read_excel("Book1.xlsx",header=None)
data=row_data.copy()
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
from keras.models import Sequential
from keras.layers import Dense
import seaborn as sns

In [4]:
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [5]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [6]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
model.fit(X_train, y_train, batch_size=10, epochs=200)

Epoch 1/200
12/12 [==============================] - 1s 2ms/step - loss: 2.4198 - accuracy: 0.3667
Epoch 2/200
12/12 [==============================] - 0s 2ms/step - loss: 2.2341 - accuracy: 0.3667
Epoch 3/200
12/12 [==============================] - 0s 3ms/step - loss: 2.0372 - accuracy: 0.3667
Epoch 4/200
12/12 [==============================] - 0s 2ms/step - loss: 1.8512 - accuracy: 0.3667
Epoch 5/200
12/12 [==============================] - 0s 2ms/step - loss: 1.6753 - accuracy: 0.3667
Epoch 6/200
12/12 [==============================] - 0s 1ms/step - loss: 1.5221 - accuracy: 0.3667
Epoch 7/200
12/12 [==============================] - 0s 2ms/step - loss: 1.3819 - accuracy: 0.3667
Epoch 8/200
12/12 [==============================] - 0s 2ms/step - loss: 1.2763 - accuracy: 0.3667
Epoch 9/200
12/12 [==============================] - 0s 2ms/step - loss: 1.1864 - accuracy: 0.3667
Epoch 10/200
12/12 [==============================] - 0s 1ms/step - loss: 1.1251 - accuracy: 0.3667
Epoch 11/

12/12 [==============================] - 0s 2ms/step - loss: 0.5247 - accuracy: 0.7833
Epoch 83/200
12/12 [==============================] - 0s 2ms/step - loss: 0.5209 - accuracy: 0.8083
Epoch 84/200
12/12 [==============================] - 0s 2ms/step - loss: 0.5167 - accuracy: 0.8083
Epoch 85/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5139 - accuracy: 0.7833
Epoch 86/200
12/12 [==============================] - 0s 2ms/step - loss: 0.5096 - accuracy: 0.8083
Epoch 87/200
12/12 [==============================] - 0s 2ms/step - loss: 0.5058 - accuracy: 0.8083
Epoch 88/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5022 - accuracy: 0.8083
Epoch 89/200
12/12 [==============================] - 0s 2ms/step - loss: 0.4989 - accuracy: 0.8417
Epoch 90/200
12/12 [==============================] - 0s 2ms/step - loss: 0.4953 - accuracy: 0.8583
Epoch 91/200
12/12 [==============================] - 0s 1ms/step - loss: 0.4926 - accuracy: 0.8667
Epoch 92/200


12/12 [==============================] - 0s 2ms/step - loss: 0.3155 - accuracy: 0.9583
Epoch 163/200
12/12 [==============================] - 0s 2ms/step - loss: 0.3141 - accuracy: 0.9583
Epoch 164/200
12/12 [==============================] - 0s 1ms/step - loss: 0.3118 - accuracy: 0.9583
Epoch 165/200
12/12 [==============================] - 0s 2ms/step - loss: 0.3098 - accuracy: 0.9583
Epoch 166/200
12/12 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.9583
Epoch 167/200
12/12 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.9583
Epoch 168/200
12/12 [==============================] - 0s 2ms/step - loss: 0.3039 - accuracy: 0.9583
Epoch 169/200
12/12 [==============================] - 0s 2ms/step - loss: 0.3025 - accuracy: 0.9583
Epoch 170/200
12/12 [==============================] - 0s 2ms/step - loss: 0.2999 - accuracy: 0.9583
Epoch 171/200
12/12 [==============================] - 0s 1ms/step - loss: 0.2980 - accuracy: 0.9583
Epoc

In [8]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [9]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
